os: linux
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: surge
  cleanup: true
  domain: https://b-radius-for-us.surge.sh
  project: ./build/
on:
  branch: master
