os: linux
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: b-radius-for-us.surge.sh
  project: /build
on:
  branch: master
